# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Unet
description: >- # this means to ignore newlines until "baseurl:"
  At the heart of the Unet project, we have UnetStack, an agent-based network stack and simulator
  designed to run highly optimized protocols for use in underwater communication networks. Although
  the default stack provides everything needed to get a basic underwater network working, the real
  power of the stack lies in its customizability and extensibility. It not only allows you to easily
  configure a network to meet your needs, but also to automate network management, develop, simulate
  and test new network protocols, and implement software-defined signaling at the physical layer.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://org-arl.github.io/unet-doc" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
